version: '3'
services:
  frontend:
    build: ./frontend
    ports:
      - "80:3000"

  backend:
    build: ./backend
    ports:
      - "3000:3000"

  database:
    image: mongo
    ports:
      - "27017:27017"
